### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by Umbrial** [Mrthomas20121-Mods/Tinkers-Reforged#26]
I can't read crash reports to save my life, but I just downloaded the latest version and it crashes when I try to launch (I'm sorry I don't know what parts of this are useful)

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/10/20 1:39 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Reforged (tinkers_reforged)
Caused by: java.lang.NoClassDefFoundError: mrthomas20121/biolib/objects/material/MaterialWrapper
at mrthomas20121.tinkers_reforged.resources.Resources.<clinit>(Resources.java:12)
at mrthomas20121.tinkers_reforged.modules.ModuleItems.preInit(ModuleItems.java:73)
at mrthomas20121.tinkers_reforged.modules.Modules.preInit(Modules.java:34)
at mrthomas20121.tinkers_reforged.TinkersReforged.preInit(TinkersReforged.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mrthomas20121.biolib.objects.material.MaterialWrapper
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 45 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 221870976 bytes (211 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID               | Version           | Source                           | Signature |
|:----- |:---------------- |:----------------- |:-------------------------------- |:--------- |
| LCH   | minecraft        | 1.12.2            | minecraft.jar                    | None      |
| LCH   | mcp              | 9.42              | minecraft.jar                    | None      |
| LCH   | FML              | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar    | None      |
| LCH   | forge            | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar    | None      |
| LCH   | mantle           | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar         | None      |
| LCH   | tconstruct       | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar | None      |
| LCH   | biolib           | 1.0.9             | biolib-1.0.9.jar                 | None      |
| LCE   | tinkers_reforged | 1.4.1             | tinkers_reforged-1.4.1.jar       | None      |

Loaded coremods (and transformers): 
GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
Pulsar/tconstruct loaded Pulses: 
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerHarvestTools (Enabled/Forced)
- TinkerMeleeWeapons (Enabled/Forced)
- TinkerRangedWeapons (Enabled/Forced)
- TinkerModifiers (Enabled/Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)
- TinkerModelRegister (Enabled/Forced)

**Comment by Mrthomas20121** [comment]
use a older version of biolib. the latest version of biolib doesn't work with tinkers reforged as stated in the changelog.
try https://www.curseforge.com/minecraft/mc-mods/biolib/files/3070909 to see if it work

**Comment by Umbrial** [comment]
ah, that makes sense. I thought I grabbed the version it asked for, but I rarely have time to read things beyond version number before pop-ups break my browser ^-^'

**Comment by Mrthomas20121** [comment]
i'm working on making it work with bio lib 1.1.1 but i don't have much time with university.

**Comment by Umbrial** [comment]
still crashing with 1.1.0 (apparently I'd grabbed 1.0.9 earlier) it will take me a second to grab that log if you need it (have to copy paste email it to myself)
