### ISSUE TITLE
Crash when hitting Ghast fireballs with the Gladius

### ISSUE THREAD

**Issue by balthierace** [Mrthomas20121-Mods/Tinkers-Reforged#6]
Without fail, whenever I hit any Ghast fireball with the Gladius, I crash and receive this error message. I am playing on the Project Ozone 3 modpack.

java.lang.ClassCastException: net.minecraft.entity.projectile.EntityLargeFireball cannot be cast to net.minecraft.entity.EntityLivingBase
	at com.mrthomas20121.tinkers_reforged.Tools.SwordGladius.dealDamage(SwordGladius.java:57)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:729)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:612)
	at slimeknights.tconstruct.library.tools.ToolCore.onLeftClickEntity(ToolCore.java:236)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:1067)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1250)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1511)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by balthierace** [comment]
I can also reproduce this crash with Ender Crystals in the End.

**Comment by balthierace** [comment]
This bug also occurs while hitting shulker bullets. It appears to apply to any non-living entity.

**Comment by Mrthomas20121** [comment]
Fixed in dev.
