### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Pantheris2019** [Mrthomas20121-Mods/Tinkers-Reforged#75]
Upon launching with tinkers reforged installed in my modpack:

-- Head --
Thread: Render thread
Suspected Mod: 
	Tinkers Reforged (tinkers_reforged), Version: 2.1.2
		Issue tracker URL: https://github.com/Mrthomas20121/Tinkers-Reforged/issues
		at TRANSFORMER/tinkers_reforged@2.1.2/mrthomas20121.tinkers_reforged.api.material.EnumMaterialStats.<clinit>(EnumMaterialStats.java:12)
Stacktrace:
	at mrthomas20121.tinkers_reforged.api.material.EnumMaterialStats.<clinit>(EnumMaterialStats.java:12) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
-- MOD tinkers_reforged --
Details:
	Mod File: /D:/MCMODS/Instances/Create The Future BEYOND THE HORIZON (1)/mods/Tinkers Reforged 1.19.2-2.1.2.jar
	Failure message: Tinkers Reforged (tinkers_reforged) has failed to load correctly
		java.lang.NoSuchFieldError: DEFAULT
	Mod Version: 2.1.2
	Mod Issue URL: https://github.com/Mrthomas20121/Tinkers-Reforged/issues
	Exception message: java.lang.NoSuchFieldError: DEFAULT
Stacktrace:
	at mrthomas20121.tinkers_reforged.api.material.EnumMaterialStats.<clinit>(EnumMaterialStats.java:12) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at mrthomas20121.tinkers_reforged.api.material.EnumMaterial.<clinit>(EnumMaterial.java:14) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at mrthomas20121.tinkers_reforged.api.material.ReforgedData.<clinit>(ReforgedData.java:16) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at mrthomas20121.tinkers_reforged.init.TinkersReforgedWorldGen.lambda$static$10(TinkersReforgedWorldGen.java:44) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?] {re:mixin}
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at mrthomas20121.tinkers_reforged.util.Helpers.mapOfKeys(Helpers.java:24) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at mrthomas20121.tinkers_reforged.init.TinkersReforgedWorldGen.<clinit>(TinkersReforgedWorldGen.java:44) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at mrthomas20121.tinkers_reforged.TinkersReforged.<init>(TinkersReforged.java:43) ~[Tinkers%20Reforged%201.19.2-2.1.2.jar%23619!/:2.1.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.7.jar%23639!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.7.jar%23638!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

New engine crashes gracefully at least.

**Comment by Mrthomas20121** [comment]
my mod is not compatible with the latest tinkers version on 1.19.2. I'm working on it but it's taking time
